### ISSUE TITLE
Social media plugins

### ISSUE THREAD

**Issue by sechon01** [kbarke05/itc210#5]

**Comment by sechon** [comment]
youtube, facebook, twitter, a one in all?

**Comment by sechon** [comment]
Social media sharing
-mashshare

**Comment by sechon** [comment]
Videos
-youtube by embedplus team
-youtube channel gallery
slider type?
-giga slider

**Comment by sechon** [comment]
facebook integration?
-facebook by facebook
-custom facebook feed by smash balloon
